language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.1
  - android-27
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - android-sdk-license-.+
  - '.+'

script:
    - ./gradlew --daemon build jacocoTestReport --info

after_success:
    - bash <(curl -s https://codecov.io/bash)
